// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyHelper.Infrastructure.MyHelperDbContext;

#nullable disable

namespace MyHelper.Infrastructure.Migrations
{
    [DbContext(typeof(MyHelperDBContext))]
    partial class MyHelperDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("MyHelper.Domain.Entities.AutoCompleteTextRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AutoCompleteTextRecords");
                });

            modelBuilder.Entity("MyHelper.Domain.Entities.LauncherItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LauncherType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LauncherItems");
                });

            modelBuilder.Entity("MyHelper.Domain.Entities.Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableLauncherByCtrlKeys")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableLauncherByMouseButton")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastWrittenTimeForTables")
                        .HasColumnType("TEXT");

                    b.Property<bool>("OpenValidPathByCtrlCC")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("MyHelper.Domain.Entities.TableColumnInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColumnComment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ColumnName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsNullable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IsPrimaryKey")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Table_Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Table_Id");

                    b.ToTable("TableColumnInfos", (string)null);
                });

            modelBuilder.Entity("MyHelper.Domain.Entities.TableInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TableComment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TableName")
                        .IsUnique()
                        .HasDatabaseName("IX_TableInfo_TableName");

                    b.ToTable("TableInfos", (string)null);
                });

            modelBuilder.Entity("MyHelper.Domain.Entities.TableColumnInfo", b =>
                {
                    b.HasOne("MyHelper.Domain.Entities.TableInfo", "TableInfo")
                        .WithMany("TableColumnInfos")
                        .HasForeignKey("Table_Id");

                    b.Navigation("TableInfo");
                });

            modelBuilder.Entity("MyHelper.Domain.Entities.TableInfo", b =>
                {
                    b.Navigation("TableColumnInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
